5.バリテーションの追加
yanbaru-expert/team_project_46 pull request #33
Opened 2021-03-20 07:11 UTC by matsumoto978

## issue 番号
close #13 

## 実装内容

- タスク4で作成した2種類のモデルに、各カラムにからデータが入らないようにするバリテーションを追加

2021-03-20 07:23 UTC, T-Tsujii requested changes

2021-03-20 07:23 UTC, T-Tsujii commented on app/models/movie.rb
> -  enum genre: {
元の記述を消してしまっています！差分は確認しましょう。

https://github.com/yanbaru-expert/team_project_46/pull/33/files

2021-03-21 04:28 UTC, T-Tsujii reviewed
LGTMです！

2021-03-21 06:06 UTC, takurofukuta approved these changes

2021-03-21 07:04 UTC, matsumoto978 commented
コメントありがとうございます。

2021-03-21 08:31 UTC, T-Tsujii approved these changes

2021-03-21 08:41 UTC, merged